# Generated by Django 3.2.5 on 2021-11-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='expertise',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], null=True, verbose_name='expertise'),
        ),
    ]
